name: CI
on:
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - run: yarn
      - run: yarn lint
      - run: yarn test
